name: Run test cases

on: [push, pull_request]

jobs:    
    run_test_cases:
        runs-on: ubuntu-latest
      
        container:
            image: erlang:22.1
        # Service containers to run with `runner-job`
        services:
          # Label used to access the service container
          rediscluster:
            image: grokzen/redis-cluster:latest
            ports:
              - 7000-7005:7000-7005
          redis:
            # Docker Hub image
            image: redis
            # Set health checks to wait until redis has started
            options: >-
              --health-cmd "redis-cli ping"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              # Maps port 6379 on service container to the host
              - 6379:6379
        steps:
            - uses: actions/checkout@v1
            - name: run test cases
              run: |
                make xref
                make eunit  
                make ct
                make cover
            - uses: actions/upload-artifact@v1
              if: always()
              with:
                name: logs
                path: _build/test/logs
            - uses: actions/upload-artifact@v1
              with:
                name: cover
                path: _build/test/cover

